import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = 
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const buildOptions = {
	entryPoints: ["main.ts"],
	outfile: "main.js",
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins
	],
	format: "cjs",
	target: "es2018",
	banner: {
		js: banner,
	},
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
};

if (!prod) {
    // Add watch option only for development builds
    buildOptions.watch = {
        onRebuild(error, result) {
            if (error) console.error("watch build failed:", error);
            else console.log("watch build succeeded:", result);
        },
    };
}

esbuild.build(buildOptions).catch((err) => {
    console.error(err);
    process.exit(1);
});

